[package]
name = "pr-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.2", features = ["derive", "std"] }
chrono = "0.4.22"
compress = "0.2.1"
